# Site
repository: sproogen/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Giovani Ângelo Silva da Nóbrega
title: Software Engineer
email: giovani.angelo@gmail.com
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
website_title: https://giovanigithub.github.io/resume

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
github_username:  GiovaniGitHub

linkedin_username: giovaninobrega

about_profile_image: images/avatar.jpeg
about_content: | # this will include new lines to allow paragraphs
  Software Engineer with 15 years of experience in the area both teaching and developing systems. 
  In the last 6 years in backend development and data engineering using languages like python, 
  javascript and scala.
  
  In view of the rapid evolution of development technologies, I don't know other ways of work other 
  than through constant learning and sharing.
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Red Ventures Brazil
        sub_title: Software Engineer
        caption: January 2022 - present
        link: https://www.redventures.com.br/
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Development of notebooks using the scala, python and SQL languages with the 
          spark framework (and pyspark) executed in DataBricks in order to extract data 
          from different data sources (log files, relational databases...).
      - layout: left
        title: Stone
        sub_title: Software Engineer
        caption: November 2020 - December 2021
        link: https://www.stone.com.br/
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Development and maintenance of systems associated with the company's billing process. 
          Technologies such as Python, NodeJS and PostgreSQL with Docker, 
          Kubernetes using Google Cloud Platform solutions were used for the development.
      - layout: left
        title: QuantticsAI
        sub_title: Software Engineer
        caption: September 2020 - December 2020 
        link: https://www.stone.com.br/
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Development of bots and web scrapers with Python and models to mining with R.
      - layout: left
        title: GTP Automation
        sub_title: Software Engineer
        caption: Juny 2019 -- November 2019 
        link: https://www.stone.com.br/
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
           Development of georeferenced image processing systems using Python tools 
           integrating with back ends developed in Java.
      - layout: left
        title: LAIS - Laboratório de Inovação Tecnologia em Saúde
        sub_title: Research and Technology Consultan
        caption: January 2015 – December 2019 
        link: https://lais.huol.ufrn.br/en/
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
            Support for research, review of articles and works for publication, 
            implementation and proposals for solutions to problems using Machine Learning, 
            Digital Image and Signal Processing and Statistical Analysis.

  # - title: Education
  #   layout: list
  #   content:
  #       - layout: left
  #       title: PhD Electrical and Computer Engineering
  #       sub_title: Federal University of Rio Grande do Norte
  #       caption: September 2011- May 2016

  #       - layout: left
  #       title: M.Sc. Systems and Computing
  #       sub_title: Federal University of Rio Grande do Norte
  #       caption: January 2009 – November 2010

  #       - layout: left
  #       title: Graduate in Technology and Software Development
  #       sub_title: Federal Institute of Education Science and Technology of Rio Grande do Norte
  #       caption: July 2004 - July 2009

  #       - layout: left
  #       title: Graduate in Mathematics
  #       sub_title: Federal University of Rio Grande do Norte
  #       caption: July 2004 - July 2009

  - title: Education
    layout: list
    content:  
      - title: PhD
        sub_title: September 2011- May 2016
        caption: Federal University of Rio Grande do Norte
        # quote: >
        #   Short institution or course description
        description: >
          PhD Electrical and Computer Engineering.
          The research was focused on the application of statistical and machine learning 
          methods for the processing of medical images.

      - layout: left
        title: Master of Sciences
        sub_title: January 2009 – November 2010
        caption: Federal University of Rio Grande do Norte
        description: >
          M.Sc Systems and Theory of Computing with emphasis on computational mathematics.

      - layout: left
        title: Degree
        sub_title: July 2004 - July 2009
        caption: Federal Institute of Education Science and Technology of Rio Grande do Norte
        description: >
          Degree in Technology and Software Development with emphasis on analysis, development
          and deployment of web systems and database administration.

      - layout: left
        title: Bachelor
        sub_title: January 1999 - March 2003
        caption: Federal University of Rio Grande do Norte
        description: >
          Bachelor in Mathematics with emphasis on analytical and pure mathematics and training 
          for teaching.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
